"============================================================"
"|                         SETTINGS                         |"
"============================================================"

"General settings"
filetype off
syntax enable
let mapleader = ","
set nocompatible
set spelllang=en_gb
set encoding=utf-8
set modelines=0
set scrolloff=3
set autoindent
set wrap
set linebreak
set list
set listchars=tab:»·,eol:¬,trail:·
set hidden
set visualbell t_vb=
set ttyfast
set backspace=indent,eol,start
set laststatus=2
set number
set relativenumber
set undofile
set undolevels=5000
set showmatch
set formatoptions=qrn1

"Tab settings"
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

"Command line settings"
set showmode
set showcmd
set wildmenu
set wildmode=list:longest

"Search settings"
set ignorecase
set smartcase
set incsearch
set hlsearch

"Directories"
set undodir=$XDG_CACHE_HOME/vim/undofiles
set directory=$XDG_CACHE_HOME/vim/swapfiles,~/tmp,/var/tmp,/tmp
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIMRUNTIME



"============================================================"
"|                          KEYMAPS                         |"
"============================================================"

"Normal mode keymaps"
nnoremap j gj
nnoremap k gk
nnoremap ; :
nnoremap : ;
nnoremap / :set hlsearch<CR>/
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <silent> <leader>w :vsplit<CR><C-w>l
nnoremap <silent> <leader>W :split<CR><C-w>j
nnoremap <silent> <leader>p :set paste!<CR>
nnoremap <silent> <leader>e :vsplit<CR><C-w>l:e $XDG_CONFIG_HOME/vim/vimrc<CR>
nnoremap <silent> <leader>E :e $XDG_CONFIG_HOME/vim/vimrc<CR>
nnoremap <silent> <leader>r :so $XDG_CONFIG_HOME/vim/vimrc<CR>
nnoremap <silent> <leader>q :q<CR>:so $XDG_CONFIG_HOME/vim/vimrc<CR>
nnoremap <silent> <leader>s :set spell!<CR>
nnoremap <silent> <leader><space> :let @/ = ""<CR>:set nohlsearch<CR>
nnoremap <silent> <leader>v V`]
nnoremap <silent> <leader>f 1z=

" requires vis plugin
vnoremap <silent> <leader>y :B w !pbcopy<CR>u

"Visual mode keymaps"
vnoremap j gj
vnoremap k gk
vnoremap ; :
vnoremap : ;
vnoremap / :set hlsearch<CR>/
vnoremap . :normal.<CR>

"Insert mode keymaps"
inoremap jj <ESC>
inoremap jJ <ESC>
inoremap Jj <ESC>
inoremap JJ <ESC>
inoremap jk <ESC>
inoremap jK <ESC>
inoremap Jk <ESC>
inoremap JK <ESC>
inoremap kj <ESC>
inoremap kJ <ESC>
inoremap Kj <ESC>
inoremap KJ <ESC>
inoremap kk <ESC>
inoremap kK <ESC>
inoremap Kk <ESC>
inoremap KK <ESC>
inoremap <C-\> <C-o>:left 0<Cr><BS>

"Command mode keymaps"
cnoremap w!! w !sudo tee > /dev/null %


"============================================================"
"|                         AUTOCMDS                         |"
"============================================================"

"Always trigger Limelight on entering Goyo mode
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!

"Always run gofmt on save"
autocmd BufWritePost *.go silent! !gofmt -w %

autocmd FileType tex inoremap ;tit \textit{}<ESC>T{i
autocmd FileType tex inoremap ;bf \textbf{}<ESC>T{i
autocmd FileType tex inoremap ;ct \cite{}<ESC>T{i
autocmd FileType tex inoremap ;se \section{}<ESC>T{i
autocmd FileType tex inoremap ;sse \subsection{}<ESC>T{i
autocmd FileType tex inoremap ;ch \chapter{}<ESC>T{i
autocmd FileType tex inoremap ;it \item
autocmd FileType tex inoremap ;co \code{}<ESC>T{i
autocmd FileType tex inoremap ;la \label{}<ESC>T{i
autocmd FileType tex inoremap ;re \ref{}<ESC>T{i
autocmd FileType tex inoremap ;eq \begin{equation} \label{}<CR>\end{equation}<ESC>O
autocmd FileType tex inoremap ;ls \begin{lstlisting}[language={Java}, caption={}, label={}]<CR>\end{lstlisting}<ESC>O<TAB>
autocmd FileType tex inoremap ;p \\<CR>\\<CR>
autocmd FileType tex nnoremap <leader>m :Make<CR>
autocmd FileType tex setlocal spell
autocmd FileType tex setlocal nonumber
autocmd FileType tex setlocal norelativenumber
autocmd BufReadPost,BufNewFile *.tex Goyo

"============================================================"
"|                         PLUGINS                          |"
"============================================================"

"Plugin setup"
set runtimepath+=$XDG_CONFIG_HOME/vim/bundle/Vundle.vim
filetype plugin indent on

"Install Vundle if it doesn't already exist"
if empty(glob(expand('$XDG_CONFIG_HOME').'/vim/bundle/Vundle.vim'))
    silent !git clone https://github.com/VundleVim/Vundle.vim.git $XDG_CONFIG_HOME/vim/bundle/Vundle.vim
endif

"Plugin list"
call vundle#begin(expand('$XDG_CONFIG_HOME').'/vim/bundle')
Plugin 'VundleVim/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'alvan/vim-closetag'
Plugin 'bspammer/InsertChar'
Plugin 'bspammer/vim-redact-pass'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'felixhummel/setcolors.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'junegunn/goyo.vim'
Plugin 'junegunn/limelight.vim'
Plugin 'mbbill/undotree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-characterize'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'wellle/targets.vim'
Plugin 'vim-scripts/vis'
call vundle#end()

"Ctrl-P settings"
let g:ctrlp_show_hidden = 1
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site|bin|lib|local|share|forums)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg|pyc|swp)$',
\}

"InsertChar settings"
nnoremap <NUL> :<C-U>call InsertChar#insert(v:count1)<CR>
nnoremap <SPACE> :<C-U>call InsertChar#insertAfter(v:count1)<CR>

"Undotree settings"
nnoremap <F5> :UndotreeToggle<CR>
let g:undotree_SplitWidth=35
let g:undotree_SetFocusWhenToggle=1
let g:undotree_WindowLayout=1
let g:undotree_HighlightChangedText = 0

"NERDTree settings"
nnoremap <C-n> :NERDTreeToggle<CR>
let g:NERDTreeDirArrowExpandable = '>'
let g:NERDTreeDirArrowCollapsible = 'v'
let g:NERDTreeNodeDelimiter = "\u00a0"

"Colorscheme settings"
"colorscheme molokai

"Goyo settings
nnoremap <silent> <leader>g :Goyo<CR>
let g:goyo_margin_top = 0
let g:goyo_margin_bottom = 0

"Limelight settings
let g:limelight_conceal_ctermfg = 'gray'
